services:
  # Backend service configuration
  - name: backend
    type: web
    runtime: node
    plan: free
    region: oregon
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production

  # Frontend service configuration
  - name: frontend
    type: web
    runtime: node
    buildCommand: "react-scripts build"
    startCommand: "react-scripts start"
    envVars:
      - key: REACT_APP_API_URL
        value: "https://api.example.com"
